### ISSUE TITLE
Fix Error in frontend

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#136]
<img width="1078" alt="Screen Shot 2022-07-08 at 15 42 52" src="https://user-images.githubusercontent.com/38043569/177932607-22ba9abf-9695-46ad-b606-18139cc95dda.png">

```
2_app-4234d03d69ccda9a.js:1 invalid sdk options object passed, falling back to default options ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "readonlySettings",
      "rpcUrl"
    ],
    "message": "Required"
  }
]
    at V (_app-4234d03d69ccda9a.js:1:1481393)
    at Ie.safeParse (_app-4234d03d69ccda9a.js:1:1483729)
    at Ie.parse (_app-4234d03d69ccda9a.js:1:1483326)
    at new RPCConnectionHandler (_app-4234d03d69ccda9a.js:1:1902744)
    at new UserWallet (_app-4234d03d69ccda9a.js:1:2133069)
    at _app-4234d03d69ccda9a.js:1:2262434
    at Object.Go [as useMemo] (framework-49f1e091cbf6b261.js:1:67605)
    at n.useMemo (framework-49f1e091cbf6b261.js:1:136649)
    at useBalance (_app-4234d03d69ccda9a.js:1:2262415)
    at I (344-1c0f556cb62d1008.js:1:3065)
```

**Comment by taijusanagi** [comment]
This happens when connecting to metamask

**Comment by taijusanagi** [comment]
It seems like this is happing in thirdweb library.

since we are using wagmi wrapped in thirdweb, so try to replace thirdweb by wagmi

**Comment by taijusanagi** [comment]
wagmi not supporting react 18 well now. 

https://github.com/tmm/wagmi/issues/307

Need to make state wrapper for wagmi

**Comment by taijusanagi** [comment]
it takes to long to investigate, I stop at 
https://github.com/kaguraswap/monorepo/pull/163

**Comment by taijusanagi** [comment]
this is fixed by wagmi replacement
